### PR TITLE
Support for stagenet

### PR DESCRIPTION
**Pull request by stoffu**
This is a preliminary PR for the pending stagenet PR: https://github.com/monero-project/monero/pull/3277

### CODE REVIEW

**Comment by moneroexamples** [comment]
Forgot to ask. What is stagenet? How is it different than testnet?

**Comment by stoffu** [comment]
This is the origin of the idea: https://github.com/monero-project/monero/issues/3017

**Comment by moneroexamples** [comment]
thanks for fast reply. Is it already live?

**Comment by stoffu** [comment]
Yes. I'm hosting an explorer here: http://162.210.173.150:8083/ which is the same IP as one of the two seed nodes.

Please note that I've applied this pending PR https://github.com/monero-project/monero/pull/3358 preemptively so that a series of successive hard forks from v2 to v7 can happen from height 32000 (which is only 300 blocks away as of now). So you'd need to build that PR if you want to try it.

**Comment by moneroexamples** [comment]
Thanks. Good to know. So this stagenet is equivalent to running testnet using latest release binaries: https://github.com/monero-project/monero/releases ?

**Comment by stoffu** [comment]
I'm not sure what you're asking. Testnet and stagenet use different seed nodes, port numbers, network IDs, etc. Also their fork heights are of course different. The idea is to keep stagenet as stable as mainnet so that people can experiment stuff on it without worrying about rollbacks which is very common on testnet.

**Comment by moneroexamples** [comment]
i'm taking about version number. current testnet is v8. so staging will be the same version as mainent (v6)?

**Comment by stoffu** [comment]
Currently it's v1, and the fork to v2 happens at 32000, followed by successive hardforks up to v7 at 37000.

**Comment by moneroexamples** [comment]
ah ok. thx for clarification.

**Comment by moneroexamples** [comment]
Hi

Did you encounter `Error: RPC error: failed to get output distribution` error in cli monero wallet when trying to make txs in stagenet? 

I'm trying to transfer from this stagenet wallet: 
> eluded extra boyfriend gels hiding waxing feline unbending drying pancakes dwindling fuming friendly pamphlet myth tepid snug budget android vogue losing each affair afraid affair

And cant seem to be able to make txs. Am at current monero master:

```
mwo:monero$ git log -1
commit 8361d60aef6e17908658128284899e3a11d808d4
Merge: 2c145f4 b1398ff
Author: Riccardo Spagni <ric@spagni.net>
Date:   Mon Mar 19 11:39:59 2018 +0200

    Merge pull request #3434
    
    b1398fff core: fix use of uninitialised data (moneromooo-monero)
```

**Comment by stoffu** [comment]
That's strange, I was able to make an outgoing transfer from that wallet: http://162.210.173.150:8083/tx/9c7a93b33e62e9cdbb0eee6f3be840a5b791a49f982afcd7863eff858768eac3

**Comment by moneroexamples** [comment]
Thanks. I will investigate more. Maybe its something got mixed with my wallet and node.

**Comment by moneroexamples** [comment]
Was trying to debug this thing, and I'm hitting this exception:

>> THROW_WALLET_EXCEPTION_IF(segregation_fork_height - d.start_height >= d.distribution.size(), error::get_output_distribution, "Distribution size too small"); 

In wallet2.cpp: https://github.com/monero-project/monero/blob/master/src/wallet/wallet2.cpp#L5836

And it happens because `segregation_fork_height` is 1000000, `d.start_height` is 33000 and `d.distribution.size()` is 8317, for `amount` of 0.

It keeps hapening from different wallets on different PCs. Do you know what is segregation fork and why its so high for stagenet?

**Comment by stoffu** [comment]
This fixes it: https://github.com/monero-project/monero/pull/3473

**Comment by moneroexamples** [comment]
Thanks. Seems to be working with patch. Later I will do more checks, and if something, I will let you know.

**Pull request merged**
