### PR TITLE
Changed mixin to ring size/ring member

### PR DESCRIPTION
**Pull request by alvinjoelsantos**
**Related PRs/Issue:** 
https://github.com/monero-project/monero-core/pull/430
https://github.com/monero-project/monero-site/pull/220
https://github.com/monero-project/monero-site/issues/83

### CODE REVIEW

**Comment by moneroexamples** [comment]
Thanks. At the moment I can't merge it as its not that simple. `ring size = mixin + 1`, so by changing `mixin` to `ring size` on index page, for example, would result in incorrect information. So minimal changes in one or two places in C++ are needed as well. 

If you want you can make these changes, and make PR for one of the development branches. For instance, the development server, http://139.162.32.245:8081/, is running this branch now for tests: 

https://github.com/moneroexamples/onion-monero-blockchain-explorer/tree/emission_rate_thread

**Comment by alvinjoelsantos** [comment]
Okay. Will look in to it.

**Comment by moneroexamples** [comment]
Thanks. The changes needed are small. For example, in this line `-1` should be removied:

https://github.com/moneroexamples/onion-monero-blockchain-explorer/blob/emission_rate_thread/src/page.h#L154

In general, just have to check where templates take mixin numbers from, and add or substract 1 from them. Please don't change variable names in C++. All explorer logic is in `page.h`.

**Comment by alvinjoelsantos** [comment]
Moved to development branch https://github.com/moneroexamples/onion-monero-blockchain-explorer/pull/61

**Pull request closed without merging**
