### PR TITLE
Ported to Aeon

### PR DESCRIPTION
**Pull request by stoffu**
Now that Aeon released a new version rebased on Monero's latest master branch (https://github.com/aeonix/aeon/releases/tag/v0.12.0.0), could you please consider adding a branch for Aeon to your repository?

Thanks!

### CODE REVIEW

**Comment by moneroexamples** [comment]
Thanks! Does aeon uses lmdb now, and does not need gigabytes of ram? The last time I tried aeon I could not run its node, thus could not do anything with it.

**Comment by stoffu** [comment]
It’s based on LMDB, yes. As you can see in the commit

**Comment by stoffu** [comment]
(Accidentally hit close button)

**Comment by moneroexamples** [comment]
OK. So I will get aeon node today I try the explorer.

**Comment by moneroexamples** [comment]
I compiles and runs well. I made new branch for it:

https://github.com/moneroexamples/onion-monero-blockchain-explorer/tree/aeon

For now I will keep it as a separate branch. Thanks again.

**Comment by stoffu** [comment]
Thank you for making a separate branch! I think it's the best approach, also done in https://github.com/sammy007/monero-stratum/tree/aeon. Closing

**Pull request closed without merging**
