### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by navegacion**
Adding an alternative block explorer.

### CODE REVIEW

**Comment by moneroexamples** [comment]
Thanks

**Comment by moneroexamples** [comment]
Moved it to clearnet versions, as alternative block explorers lists fully independent explores (i.e., those not based on the onion explorer).

**Comment by navegacion** [comment]
Thank you.

**Comment by moneroexamples** [comment]
good job btw on the customisation of the explorer :-)

**Comment by navegacion** [comment]
Thank you, I appreciate the support!

**Pull request merged**
