### PR TITLE
Additional Styling

### PR DESCRIPTION
**Pull request by dternyak**
april15moneroblockchain

Potential white version that @Gingeropolous may be interested in for xmrchain.net. Just need to apply your same CSS tweaks to invert the colors. 

white-moneroblockchain

### CODE REVIEW

**Comment by dternyak** [comment]
Here's the updated detail view 


detail

**Comment by dternyak** [comment]
Sweet! Let me know when its up! Excited to see it with real data.

**Comment by moneroexamples** [comment]
It is already up. I made one comment also, but cant find it now. Maybe didnt save it. Anyway I write again.


Thanks for PRs. The new changes are already live: http://139.162.32.245:8081/

First impressions are good. I like the input fields and blue button. Not sure about the table borders though. On block page (e.g., http://139.162.32.245:8081/block/1289479) there is not much text anyway, and table borders seem to dominate over the text. 

Also regarding the tables. In tor browser (http://libwh5lvouddzei4.onion/) the index page is too wide now. I think the framework made the table too wide and not adapt well to tor browser width. In comparison, this is older instance of the onion explorer (dvwae436pd7nt4bc.onion). It fits better to tor browser width, even though it has one extra column (rct/type), as compared to the current version. In the current version this was removed to made the index page width agree well with tor browser. Thus need to check why this framework made the index page so wide.

**Comment by dternyak** [comment]
@moneroexamples I can take out some of tables on the block page, agree it's a bit heavy. I'm also looking at some other frameworks including https://picnicss.com/ which has better out-of-the-box styling/components.

This would entail a complete re-design, as the reason I initially went with pure-css is because it easily fits into your existing css, but I don't think this will be the case with picnic (which is a good and bad thing).

I've been developing "blind" because I can't get the actual back=end to run based on https://github.com/moneroexamples/onion-monero-blockchain-explorer/issues/54 (and probably a lack of trying), but I'm happy to try harder so that I can build a better UI for the site while having access to a dev environment.

**Comment by moneroexamples** [comment]
What kind of errors you get when building and what os? For building test branches (e.g. pure_css_try), you need latest development version of monero. If you can list compilation problems or issues I try helping out. 

All the examples are developed and tested on linux, so can help only with Linux compilations. Can't help much with windows or mac os unfortunately.

**Pull request merged**
